travis:
  secure:
    BINSTAR_TOKEN: e1u8gVJFhID4Bxvv6mq22mAbQ12pHGQMEaXIv2PrcICznpgQ/CvgLh4Cj4SlJh/v/3xs0R1PufgenO/Pxenx9yMog2n/MRpB+u8eUejSvMGYedRuJYmizZRgigYA9rBTdh4iXeU+mxdzIVqjPY7kvBMvEAaRODVrWyQgzh1PzL2dCeyPrDa7w3Ot89V9cXpFA8qzKgC1ojbODlcDBZOubEKYHm3+VOf4xhH0nQxy/ZtJUSV32kqReb6pddnS34bkg/AyhEjqlgVPzRDfXbOBUh8/JST8TRIJCBL+IOFnbmTiNF9usLfhLunQZjnVFK+VI878maXMkoXXxlHnjH7jfpBuDBcAxMSV95IcJbH+oqPGFMgt6vparCTHB6/EjYQxdCPuGLW+Lpke4qlOKJ6QT/kJ55kXh7uGOsCNMQktLnHL8ysqUVRBkl3OE9sCtmkBkmm8laM1y3uTi869y5ozfTN3Byfbo6GSMRyTGR4g4VYSbRY39oVGAP3dKSoTPpAKBt41Z8WDOviLmfL537fX4Ziu9HcZXD9DvGQsDuOMOpg+CIMT5t7LOqEAgKfd4OKiCu9ur9RBphXipIJ0xa/vp80smyKWqpaSZWv8NmjYkZRyBtjD/8f9/1Ig915slfcBbHVkSlrukBXzH+3+vGlFzcL77Gkf7MuYaaS25k4xOcI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
