travis:
  secure:
    BINSTAR_TOKEN: LOnqUKV1lqeOnn/UVeQVkWHf+8ORxQeAq5L53ka/ytk9js1/ygpxK5ruzDc0Gq2HLGyQB3jvZSCzyK9ITY3lD47FyAHpAhV48J3DJZ9aeeki7nPdHlJG6mwuYHi9lf2cfOFjU9g3ETvX+tr/DfC+etBhAVRlWqb2+2/ZGr6ZOrS3YTi6T/0HRBck3miBMYmTDrcOS0LunuRS01GseSlMOa4ip9zGaOpNH6AVua08CibHuyPHvMFB9YKouArDKilStSA+jlMj2S8Lh0t7mwgqWeZ5/3p1miDS6TC3chxX7mPUBCDh7tLP6ciPbZCXvXYbjbEN05BbviriM3aQmEizQuvX3zqQ8prBNOdPvQgj6BeVI2sHpwbqWcvNQv416yH/SEZb7swsjUV/kFxvWaQZGclrsAdYWE7TF/B29qoKx/puasiAF9wQrcR6FjeJApYjrfzpVeb03IXsKrCdC3s1gaJeyMXQ05aSvoJGA9esqE/V320wpbP9DC0YZyBom4lyFL9j8XOZNifV/qNmN54KsVYMgN9EXMCTNt6BzR2QaTv49cNMN1qDVqmcIzoiKbSwuLBT32+UklgLJIw0WHG2CxpKGrihR7iu2dkQ3HA//MnImrCd5Y5bBuiofOiMDwHxJK+M0pTDtOEZGpsf8bnXiLtLg8NPYNMqxOHQmPl7XEs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
