travis:
  secure:
    BINSTAR_TOKEN: YGalUxuK/rHfgg2q3QL1ku8zLXSrll1GrUgCRcsruzWOHqQ9qrNcrw4g74YhnumAr736NUyYHhJaiJnH1OtW9AWDJL3rw4NSgt0VoRgWmBRSyi/GUhoFpWyCTB+O0XbwHT0757V+ZoomtOmNKQp3Fr8xLNf8YU6G2COAluKGrzlk6/PBaAw3q1Mb3XKlDUeGeYpEemRZ2L0S9iFmISpu7qQG/OAbRKbZ5J0GDdANHo3jzarU62F4cP3smqnri+M1HOrAhElvFoK/fakkXsLr1WvR2zGo010pXKPK43yj2dehlVM1kR4QD4hqxfB/2ZExVI044L/tNgoykJRwXxUSiieiam62nOM3ABajaZTMVT/o0O2gPQ7y0V7+BthR8/N7uCOROe19oDUXX6aW2e+HF3zQfc9VUzQ9nk2I3OLHWnKyjn2ix8144F0xM5FRgXEPgTz/KNQ9qhb3bwqV+EsDLv2uvGlYi5eeTnDeiRK15nynEhEkbqVOfH2FVI69F9zoJNOc7UuiJpg7B9WDhd0VnbtAni/e28bof9lRcjv1N9wJKmRatyMyBtVZw4GMY/U6tGGgCzNB6u4sIJdKhIv+RQMxtY21ltaW/XB252T7LQ2MVwHhsfkiKMDFt7g9Vr6w0ui3nGqVTCoi/lZ2JLu3IFIdF8O9HkvbjSv0gUj00OY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
